openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'SystemsArchitecture Lab2'
  description: API взаимодеиствия с сервисом пользователей
servers:
  - url: http://localhost:8080
    description: Example server
paths:
  /user:
    get:
      summary: Получить информацию о пользователе по логину или информацию о всех пользователях
      parameters:
      - name: login
        description: Логин пользователя (если не указан, то в ответе будет информацию обо всех пользователях)
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Информация о найденном пользователе или, если не указан логин, список всех пользователей
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        404:
          description: Пользователя с таким логином не существует (если был запрос по логину) или никаких записей о пользователях не найдено (если был общий запрос) 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Добавить информацию о новом пользователе
      requestBody:
        description: JSON, содержащий информацию о новом пользователе
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  example: 'Ivan'
                last_name:
                  type: string
                  example: 'Ivanov'
                email:
                  type: string
                  example: 'ivanivanov@email.com'
                title:
                  type: string
                  example: 'michael36'
                login:
                  type: string
                  example: 'login'
                password:
                  type: string
                  example: 'password'
      responses:
        '200':
          description: Идентификатор нового пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        400:
          description: Пользователь с таим логином уже существует или имя, фамилия или электронная почта не удовлетворяют формату или не вся необходимая информация была предоставлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Обновить информацию о пользователе
      parameters:
      - name: login
        description: Логин обновляемого пользователя
        in: query
        required: true
        schema:
          type: string
      - name: password
        description: Пароль обновляемого пользователя (для сгенерированных пользователей пароль всегда password)
        in: query
        required: true
        schema:
          type: string
      requestBody:
        description: JSON, содержащий обновленную информацию о пользователе
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  example: 'Ivan'
                last_name:
                  type: string
                  example: 'Ivanov'
                email:
                  type: string
                  example: 'ivanivanov@email.com'
                title:
                  type: string
                  example: 'michael36'
                password:
                  type: string
                  example: 'password'
      responses:
        '200':
          description: Идентификатор обновленного пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        400:
          description: Логин пользователя или пароля неверен, или информация для обновления отсутствует или фамилия или имя или почта не удовлетворяют формату
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Удалить информацию о пользователе
      parameters:
      - name: login
        description: Логин удаляемого пользователя
        in: query
        required: true
        schema:
          type: string
      - name: password
        description: Пароль удаляемого пользователя (для сгенерированных пользователей пароль всегда password)
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Идентификатор удаленного пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        400:
          description: Пользователя с таким логином не существует или пароль не верен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /user/search:
    get:
      summary: Получить информацю о пользователях по префиксам имени и фамилии
      parameters:
      - name: first_name
        description: Префикс имени
        in: query
        required: true
        schema:
          type: string
      - name: last_name
        description: Префикс фамилии
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Список пользователей, удовлетворяющих префиксам
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/users'
        400: 
          description: Префикс фамилии или имени не был предоставлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404: 
          description: Пользователей, удовлетворяющих префиксам не найдено
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /user/auth:
    get:
      summary: Аутентифицировать пользователя и получить JWT-токен для обращения к остальным сервисам
      security:
        - basicAuth: []
      responses:
        '200':
          description: Идентификатор пользователя и его JWT-токен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/auth_info'
        401: 
          description: Схема авторизации отличается от Basic или логин или пароль неверны
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'     

components:
  schemas:
    user_id:
      description: Уникальный идентификатор пользователя
      type: integer
    auth_info:
      description: Информация для аутентификации пользователя в остальных сервисах
      type: object
      required:
        - id
        - token
      properties:
        id:
          $ref: '#/components/schemas/user_id'
        token:
          type: string
    users:
      type: array
      items:
        $ref: '#/components/schemas/user'
    user:
      type: object
      required:
        - id
        - first_name
        - last_name
        - email
        - title
        - login
        - password
      properties:
        id:
          $ref: '#/components/schemas/user_id'
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        title:
          type: string
        login:
          type: string
        password:
          type: string
    Error:
      type: object
      required:
        - detail
        - instance
        - status
      properties:
        detail:
          description: Описание причины ошибки
          type: string
        instance:
          description: Путь
        status:
          description: Код ошибки
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic